create table "public"."member_invitations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "member_id" bigint not null,
    "email" text not null,
    "invited_by" bigint not null
);


create table "public"."profiles" (
    "created_at" timestamp with time zone not null default now(),
    "email" text not null,
    "user_id" uuid not null
);


CREATE UNIQUE INDEX member_invitations_pkey ON public.member_invitations USING btree (id);

CREATE UNIQUE INDEX profiles_email_key ON public.profiles USING btree (email);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (user_id);

alter table "public"."member_invitations" add constraint "member_invitations_pkey" PRIMARY KEY using index "member_invitations_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."member_invitations" add constraint "public_member_invitations_invited_by_fkey" FOREIGN KEY (invited_by) REFERENCES circle_members(id) ON DELETE CASCADE not valid;

alter table "public"."member_invitations" validate constraint "public_member_invitations_invited_by_fkey";

alter table "public"."member_invitations" add constraint "public_member_invitations_member_id_fkey" FOREIGN KEY (member_id) REFERENCES circle_members(id) ON DELETE CASCADE not valid;

alter table "public"."member_invitations" validate constraint "public_member_invitations_member_id_fkey";

alter table "public"."profiles" add constraint "profiles_email_key" UNIQUE using index "profiles_email_key";

alter table "public"."profiles" add constraint "public_profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "public_profiles_user_id_fkey";

grant delete on table "public"."member_invitations" to "anon";

grant insert on table "public"."member_invitations" to "anon";

grant references on table "public"."member_invitations" to "anon";

grant select on table "public"."member_invitations" to "anon";

grant trigger on table "public"."member_invitations" to "anon";

grant truncate on table "public"."member_invitations" to "anon";

grant update on table "public"."member_invitations" to "anon";

grant delete on table "public"."member_invitations" to "authenticated";

grant insert on table "public"."member_invitations" to "authenticated";

grant references on table "public"."member_invitations" to "authenticated";

grant select on table "public"."member_invitations" to "authenticated";

grant trigger on table "public"."member_invitations" to "authenticated";

grant truncate on table "public"."member_invitations" to "authenticated";

grant update on table "public"."member_invitations" to "authenticated";

grant delete on table "public"."member_invitations" to "service_role";

grant insert on table "public"."member_invitations" to "service_role";

grant references on table "public"."member_invitations" to "service_role";

grant select on table "public"."member_invitations" to "service_role";

grant trigger on table "public"."member_invitations" to "service_role";

grant truncate on table "public"."member_invitations" to "service_role";

grant update on table "public"."member_invitations" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


